---
title: "LAI and Cab inversion"
author: "Xuerui Guo"
date: '2025-06-23'
output: pdf_document
---
```{r libraries, message = FALSE}
rm(list = ls())
setwd("E:/2023_process/Mica_LAI_Cab_PROSAIL_inversion")
data_dir <- "E:/2023_process" 
# number of cores to use (for parallel computations)
# change if you don't/can't use all
ncpus <- parallel::detectCores()-2
#devtools::install_github('jbferet/prosail')

# for multicore processing/to speed things up
library(snowfall)
# PROSAIL simulations(old and new version)
library(hsdar) 
#library(ccrtm)
library(prosail)
# machine learning workflows
library(caret) 
# efficient implementation of random forest
library(ranger)
# Latin hypercube sampling (smart sampling for machine learning)
library(lhs)
# computation of solar angles
library(insol)
library(lubridate)
# working with raster images
library(raster)
# visualisation
library(ggplot2)
# working with data.frames
library(dplyr)
library(reshape2)
# Latin hypercube sampling (smart sampling for machine learning)
library(lhs)
library(prospect)
# load some useful functions wroten in /R folder
source("R/SpecPROSPECT_FullRange-data.R")

# RMSE definition
source("R/rmse.R")

source("R/SpecATM-data.R")
#source("R/Lib_PROSAIL.R")
#source("R/Lib_PROSAIL_LUT.R")
#source("R/SpecATM.R")
#devtools::install_gitlab('jbferet/prosail')

source("R/SpecSOIL-data.R")

#devtools::install_github('jbferet/prospect')
# the wavelengths simulated by PROSAIL
# prosail_wl <- PROSAIL()@wavelength
#install.packages('C:/Users/xu.guo/Downloads/hsdar_1.0.3.tar.gz', repos = NULL)
```

# PROSAIL inversion from prosail::Generate_LUT_PROSAIL

```{r inversion through prosail::Generate_LUT_PROSAIL, fig.path='C:/Users/xu.guo/Desktop/AgroC_SCOPE project/LAI_inversion/',}

# define paremertization for truncated Gaussians

#in prosail:: PROSPECT, it assume PROSPECT-PRO was called with LMA set to 0, we pretend that PROSPECT-D is called with PROT and CBC set to 0

#' @format A data frame with 10 rows and 6 variables:
#'  - *N*: leaf structure parameter
#'  - *CHL*: Chlorophyll content
#'  - *CAR*: carotenoid content
#'  - *ANT*: anthocyanin content
#'  - *EWT*: Equivalent water thickness
#'  - *LMA*: Leaf Mass per Area
#'  
"Input_PROSAIL"
#The same setting for prosail::PRO4SAIL
#In prosail::Generate_LUT_PROSAI
nbSamples<-5000
InputPROSAIL<- list()
TgaussParms <- list()
TgaussParms$min <- data.frame('N' = 1.0,'CHL' = 0, 'CAR' = 0,'ANT' = 0.56, 'EWT' = 0.004, 'LMA' = 0.00166,'lai' = 0, 'LIDFa' = 25,   'fraction_brown' = 0.0, 'q'='0.1','psoil' = 0.5,'TypeLidf'=2,'tts'=30,'tto'=0,'psi'=0)
TgaussParms$max <- data.frame('N' = 2.5, 'CHL' = 80,'CAR' = 25.28, 'ANT' = 2.81,'EWT' = 0.034,'LMA' = 0.0331,'lai' = 8, 'LIDFa' = 78,  'fraction_brown' = 1, 'q'='0.1','psoil' = 0.5,'TypeLidf'=2,'tts'=30,'tto'=0,'psi'=0)
TgaussParms$mean <- data.frame('N' = 1.6, 'CHL' = 44.8,'CAR' = 8.84, 'ANT' = 1.23,'EWT' = 0.0203, 'LMA' = 0.005575,'lai' = 3.96, 'LIDFa' = 61,    'fraction_brown' = 0.17, 'q'='0.1','psoil' = 0.5,'TypeLidf'=2,'tts'=30,'tto'=0,'psi'=0)
TgaussParms$sd <- data.frame('N' = 0.3, 'CHL' = 12.2,'CAR' = 5.14,  'ANT' = 0.36,'EWT' = 0.0062, 'LMA' = 0.0008,
'lai' = 2.00, 'LIDFa' = 13, 'fraction_brown' = 0.31, 'q'='0','psoil' =
  0,'TypeLidf'=0,'tts'=0,'tto'=0,'psi'=0)

# get distribution corresponding to Gaussian

for (parm in names(TgaussParms$min)){
  set.seed(42)
  InputPROSAIL[[parm]] <- truncnorm::rtruncnorm(n = nbSamples,a = TgaussParms$min[[parm]], b =TgaussParms$max[[parm]],mean = TgaussParms$mean[[parm]], sd = TgaussParms$sd[[parm]])
  InputPROSAIL[[parm]] <- array(InputPROSAIL[[parm]],dim = c(nbSamples,1))
}
InputPROSAIL<- data.frame(InputPROSAIL)
class(InputPROSAIL)
# default values
InputPROSAIL$PROT<-0
InputPROSAIL$CBC<-0


#if TypeLidf ==1, LIDFa controls the average leaf slope if TypeLidf ==2,LIDFa controls the average leaf angle numeric.
InputPROSAIL$TypeLidf <-2
# set Hotspot parameter q to 0.1
InputPROSAIL$q <- 0.1


InputPROSAIL$tts <- 30
InputPROSAIL$tto <- 0
InputPROSAIL$psi <- 0
# default value: Solid angle for incident light at surface of leaf (simulation of roughness)

InputPROSAIL$psoil <- 0.5

class(InputPROSAIL)

colnames(InputPROSAIL)
SpecPROSPECT <-  seq(400, 2500, by = 1)
class(SpecPROSPECT )

res <- Generate_LUT_PROSAIL(InputPROSAIL =InputPROSAIL, SpecPROSPECT =SpecPROSPECT_FullRange , BandNames = NULL,SpecSOIL=SpecSOIL, SpecATM = SpecATM, SAILversion = '4SAIL',BrownLOP = NULL)

#ls(res)
#class(res$BRF)

#hsdar::speclib
wavelengths <- seq(400, 2500, by = 1)
spectra_data <- matrix(rnorm(length(wavelengths)), ncol = length(wavelengths))  # Example spectral data matrix

spectra_data<-res$BRF
# Creating a Speclib object
spectra_data <- as.matrix(spectra_data)  # Convert to matrix if not already
wavelengths <- as.numeric(wavelengths) 
my_speclib <- hsdar::speclib(spectra_data, w = wavelengths)
png("output_plot.png", width = 800, height = 600, res = 100)
# Your plotting code here

plot(my_speclib)
dev.off()
```
```{r}

## Create spectral response with gaussian density function
SRFraw<- read.csv('Micasense_Spectral_Response.csv',header = TRUE,sep = '')
center<- c(475,560,668,840,717)
fwhm <- c(20,20,10,40,10)
wl  <- c(400:2500)
weights<-cbind(SRFraw$X475,SRFraw$X560,SRFraw$X668,SRFraw$X840,SRFraw$X717)
#gaussian distribution example
response_gaussian <- speclib(t(sapply(center, function(center, wl, fwhm)
{
  a <- dnorm(wl, mean = center, sd = fwhm/2)
  a <- (a-min(a))/(max(a) - min(a))
  return(a)
}, wl, fwhm)), wl)


response<-speclib(weights, wl)

#Plot response functions
for (i in 1:5)
plot(response[i], new = i == 1, col = c("blue", "green", "red","brown","gray")[i])

```
# resampling, from continuous spectral to separate bands, with output from hsdar::PROSAIL

```{r}
#resampling, from continuous spectral to separate bands
lut_bands_select <- c(475,560,668,840,717)
 # define the sensor.characteristics of to Micasense (could also be a speparate .R file as a function)
Micasense <- read.table("Mica_center.csv", col.names = "center")
Micasense$center<- c(475,560,668,840,717)
Micasense$fwhm <- c(20,20,10,40,10)
SRFraw<- read.csv('Micasense_Spectral_Response.csv',header = TRUE,sep = '')
lut_forward <- as.data.frame(hsdar::spectralResampling(my_speclib, sensor = Micasense,response_function = response,rm.NA = TRUE, continuousdata = "auto")@spectra@spectra_ma)


lut_forward_gaussian <- as.data.frame(hsdar::spectralResampling(my_speclib, sensor = Micasense,response_function = response_gaussian,rm.NA = TRUE, continuousdata = "auto")@spectra@spectra_ma)
 # name the columns = spectral bands
#check the differences between normal resampling to weightdifference resampling
names(lut_forward) <- paste0("B", c(1:3,5:4))
names(lut_forward_gaussian) <- paste0("B", c(1:3,5:4))
head(lut_forward)
head(lut_forward_gaussian)

#run the following two lines When apply to the stack image with B1-B5 order
#lut_forward_gaussian %>% relocate(B1, B2,B3,B4,B5)
#lut_forward<-lut_forward %>% relocate(B1, B2,B3,B4,B5)


```


```{r drone image, echo=TRUE}
# Load necessary libraries
library(raster)
library(dplyr)
library(future)
library(raster)
library(dplyr)
library(snowfall)

# Monitor memory usage
memory.limit(size = 3000)  
# Read the Mica dataset
Mica_rst <- brick("E:/2023_process/20230328_final_process/Composite_20230328_Selhausen_ICOS_1m.tif")
names(Mica_rst) <- c("B1", "B2", "B3", "B5", "B4")


# Mica values as data.frame
Mica_values_df <- as.data.frame(values(Mica_rst))

names(Mica_values_df) <- c("B1","B2","B3","B5","B4")
# LUT inversion
Mica_values_df[is.na(Mica_values_df)] <- -9999
# here start a local cluster to use more CPU cores for the inversion
sfInit(TRUE, ncpus)
sfLibrary(dplyr)

# Export necessary variables and functions
sfExport(list = c("Mica_values_df", "InputPROSAIL", "lut_bands_select", "lut_forward", "rmse"))

# Function to process each row
process_row <- function(i) {
  obs <- as.numeric(Mica_values_df[i,])
  err <- apply(lut_forward, MARGIN = 1, function(x) rmse(x, obs))
  lut_idx_min <- which.min(err)
  InputPROSAIL[lut_idx_min,] %>%
    mutate(RMSE = err[lut_idx_min])
}

# Process in chunks to manage memory
chunk_size <- 1000  # Adjust based on memory constraints
n_chunks <- ceiling(nrow(Mica_values_df) / chunk_size)

lut_inv_list <- vector("list", n_chunks)

system.time({
  for (chunk in seq_len(n_chunks)) {
    start_idx <- (chunk - 1) * chunk_size + 1
    end_idx <- min(chunk * chunk_size, nrow(Mica_values_df))
    lut_inv_list[[chunk]] <- sfLapply(start_idx:end_idx, process_row) %>% bind_rows()
  }
})

lut_inv <- bind_rows(lut_inv_list)

# Stop the cluster
sfStop()
ncell(Mica_rst)

# Create empty raster object and fill with LAI values
Mica_LAI_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
Mica_Cab_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)

# Create empty raster object and fill with LIDFa values
Mica_LIDFa_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
values(Mica_LIDFa_rst) <- lut_inv$LIDFa
values(Mica_LAI_rst) <- lut_inv$lai
values(Mica_Cab_rst) <- lut_inv$CHL
# Specify the directory where you want to save the file
data_dir <- "E:/2023_process/20230328_final_process/"
writeRaster(Mica_LAI_rst, filename = file.path(data_dir, "Mica_LAI_20230328_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_Cab_rst, filename = file.path(data_dir, "Mica_Cab_20230328_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_LIDFa_rst, filename = file.path(data_dir, "Mica_LIDFa_20230328_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
```
```{r drone image, echo=TRUE}
# Load necessary libraries
library(raster)
library(dplyr)
library(future)
library(raster)
library(dplyr)
library(snowfall)

# Monitor memory usage
memory.limit(size = 3000)  
# Read the Mica dataset
Mica_rst <- brick("E:/2023_process/20230419_final_process/Composite_20230419_Selhausen_ICOS_1m.tif")
names(Mica_rst) <- c("B1", "B2", "B3", "B5", "B4")


# Mica values as data.frame
Mica_values_df <- as.data.frame(values(Mica_rst))

names(Mica_values_df) <- c("B1","B2","B3","B5","B4")
# LUT inversion
Mica_values_df[is.na(Mica_values_df)] <- -9999
# here start a local cluster to use more CPU cores for the inversion
sfInit(TRUE, ncpus)
sfLibrary(dplyr)

# Export necessary variables and functions
sfExport(list = c("Mica_values_df", "InputPROSAIL", "lut_bands_select", "lut_forward", "rmse"))

# Function to process each row
process_row <- function(i) {
  obs <- as.numeric(Mica_values_df[i,])
  err <- apply(lut_forward, MARGIN = 1, function(x) rmse(x, obs))
  lut_idx_min <- which.min(err)
  InputPROSAIL[lut_idx_min,] %>%
    mutate(RMSE = err[lut_idx_min])
}

# Process in chunks to manage memory
chunk_size <- 1000  # Adjust based on memory constraints
n_chunks <- ceiling(nrow(Mica_values_df) / chunk_size)

lut_inv_list <- vector("list", n_chunks)

system.time({
  for (chunk in seq_len(n_chunks)) {
    start_idx <- (chunk - 1) * chunk_size + 1
    end_idx <- min(chunk * chunk_size, nrow(Mica_values_df))
    lut_inv_list[[chunk]] <- sfLapply(start_idx:end_idx, process_row) %>% bind_rows()
  }
})

lut_inv <- bind_rows(lut_inv_list)

# Stop the cluster
sfStop()
ncell(Mica_rst)

# Create empty raster object and fill with LAI values
Mica_LAI_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
Mica_Cab_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)

# Create empty raster object and fill with LIDFa values
Mica_LIDFa_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
values(Mica_LIDFa_rst) <- lut_inv$LIDFa
values(Mica_LAI_rst) <- lut_inv$lai
values(Mica_Cab_rst) <- lut_inv$CHL
# Specify the directory where you want to save the file
data_dir <- "E:/2023_process/20230419_final_process/"
writeRaster(Mica_LAI_rst, filename = file.path(data_dir, "Mica_LAI_20230419_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_Cab_rst, filename = file.path(data_dir, "Mica_Cab_20230419_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_LIDFa_rst, filename = file.path(data_dir, "Mica_LIDFa_20230419_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
```




```{r drone image, echo=TRUE}
# Load necessary libraries
library(raster)
library(dplyr)
library(future)
library(raster)
library(dplyr)
library(snowfall)

# Monitor memory usage
memory.limit(size = 3000)  
# Read the Mica dataset
Mica_rst <- brick("E:/2023_process/20230503_final_process/Composite_20230503_Selhausen_ICOS_1m.tif")
names(Mica_rst) <- c("B1", "B2", "B3", "B5", "B4")


# Mica values as data.frame
Mica_values_df <- as.data.frame(values(Mica_rst))

names(Mica_values_df) <- c("B1","B2","B3","B5","B4")
# LUT inversion
Mica_values_df[is.na(Mica_values_df)] <- -9999
# here start a local cluster to use more CPU cores for the inversion
sfInit(TRUE, ncpus)
sfLibrary(dplyr)

# Export necessary variables and functions
sfExport(list = c("Mica_values_df", "InputPROSAIL", "lut_bands_select", "lut_forward", "rmse"))

# Function to process each row
process_row <- function(i) {
  obs <- as.numeric(Mica_values_df[i,])
  err <- apply(lut_forward, MARGIN = 1, function(x) rmse(x, obs))
  lut_idx_min <- which.min(err)
  InputPROSAIL[lut_idx_min,] %>%
    mutate(RMSE = err[lut_idx_min])
}

# Process in chunks to manage memory
chunk_size <- 1000  # Adjust based on memory constraints
n_chunks <- ceiling(nrow(Mica_values_df) / chunk_size)

lut_inv_list <- vector("list", n_chunks)

system.time({
  for (chunk in seq_len(n_chunks)) {
    start_idx <- (chunk - 1) * chunk_size + 1
    end_idx <- min(chunk * chunk_size, nrow(Mica_values_df))
    lut_inv_list[[chunk]] <- sfLapply(start_idx:end_idx, process_row) %>% bind_rows()
  }
})

lut_inv <- bind_rows(lut_inv_list)

# Stop the cluster
sfStop()
ncell(Mica_rst)

# Create empty raster object and fill with LAI values
Mica_LAI_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
Mica_Cab_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)

# Create empty raster object and fill with LIDFa values
Mica_LIDFa_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
values(Mica_LIDFa_rst) <- lut_inv$LIDFa
values(Mica_LAI_rst) <- lut_inv$lai
values(Mica_Cab_rst) <- lut_inv$CHL
# Specify the directory where you want to save the file
data_dir <- "E:/2023_process/20230503_final_process/"
writeRaster(Mica_LAI_rst, filename = file.path(data_dir, "Mica_LAI_20230503_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_Cab_rst, filename = file.path(data_dir, "Mica_Cab_20230503_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_LIDFa_rst, filename = file.path(data_dir, "Mica_LIDFa_20230503_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
```






```{r drone image, echo=TRUE}
# Load necessary libraries
library(raster)
library(dplyr)
library(future)
library(raster)
library(dplyr)
library(snowfall)

# Monitor memory usage
memory.limit(size = 3000)  
# Read the Mica dataset
Mica_rst <- brick("E:/2023_process/20230613_final_process/Composite_20230613_Selhausen_ICOS_1m.tif")
names(Mica_rst) <- c("B1", "B2", "B3", "B5", "B4")


# Mica values as data.frame
Mica_values_df <- as.data.frame(values(Mica_rst))

names(Mica_values_df) <- c("B1","B2","B3","B5","B4")
# LUT inversion
Mica_values_df[is.na(Mica_values_df)] <- -9999
# here start a local cluster to use more CPU cores for the inversion
sfInit(TRUE, ncpus)
sfLibrary(dplyr)

# Export necessary variables and functions
sfExport(list = c("Mica_values_df", "InputPROSAIL", "lut_bands_select", "lut_forward", "rmse"))

# Function to process each row
process_row <- function(i) {
  obs <- as.numeric(Mica_values_df[i,])
  err <- apply(lut_forward, MARGIN = 1, function(x) rmse(x, obs))
  lut_idx_min <- which.min(err)
  InputPROSAIL[lut_idx_min,] %>%
    mutate(RMSE = err[lut_idx_min])
}

# Process in chunks to manage memory
chunk_size <- 1000  # Adjust based on memory constraints
n_chunks <- ceiling(nrow(Mica_values_df) / chunk_size)

lut_inv_list <- vector("list", n_chunks)

system.time({
  for (chunk in seq_len(n_chunks)) {
    start_idx <- (chunk - 1) * chunk_size + 1
    end_idx <- min(chunk * chunk_size, nrow(Mica_values_df))
    lut_inv_list[[chunk]] <- sfLapply(start_idx:end_idx, process_row) %>% bind_rows()
  }
})

lut_inv <- bind_rows(lut_inv_list)

# Stop the cluster
sfStop()
ncell(Mica_rst)

# Create empty raster object and fill with LAI values
Mica_LAI_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
Mica_Cab_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)

# Create empty raster object and fill with LIDFa values
Mica_LIDFa_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
values(Mica_LIDFa_rst) <- lut_inv$LIDFa
values(Mica_LAI_rst) <- lut_inv$lai
values(Mica_Cab_rst) <- lut_inv$CHL
# Specify the directory where you want to save the file
data_dir <- "E:/2023_process/20230613_final_process/"
writeRaster(Mica_LAI_rst, filename = file.path(data_dir, "Mica_LAI_20230613_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_Cab_rst, filename = file.path(data_dir, "Mica_Cab_20230613_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_LIDFa_rst, filename = file.path(data_dir, "Mica_LIDFa_20230613_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
```







```{r drone image, echo=TRUE}
# Load necessary libraries
library(raster)
library(dplyr)
library(future)
library(raster)
library(dplyr)
library(snowfall)

# Monitor memory usage
memory.limit(size = 3000)  
# Read the Mica dataset
Mica_rst <- brick("E:/2023_process/20230710_final_process/Composite_20230710_Selhausen_ICOS_1m.tif")
names(Mica_rst) <- c("B1", "B2", "B3", "B5", "B4")


# Mica values as data.frame
Mica_values_df <- as.data.frame(values(Mica_rst))

names(Mica_values_df) <- c("B1","B2","B3","B5","B4")
# LUT inversion
Mica_values_df[is.na(Mica_values_df)] <- -9999
# here start a local cluster to use more CPU cores for the inversion
sfInit(TRUE, ncpus)
sfLibrary(dplyr)

# Export necessary variables and functions
sfExport(list = c("Mica_values_df", "InputPROSAIL", "lut_bands_select", "lut_forward", "rmse"))

# Function to process each row
process_row <- function(i) {
  obs <- as.numeric(Mica_values_df[i,])
  err <- apply(lut_forward, MARGIN = 1, function(x) rmse(x, obs))
  lut_idx_min <- which.min(err)
  InputPROSAIL[lut_idx_min,] %>%
    mutate(RMSE = err[lut_idx_min])
}

# Process in chunks to manage memory
chunk_size <- 1000  # Adjust based on memory constraints
n_chunks <- ceiling(nrow(Mica_values_df) / chunk_size)

lut_inv_list <- vector("list", n_chunks)

system.time({
  for (chunk in seq_len(n_chunks)) {
    start_idx <- (chunk - 1) * chunk_size + 1
    end_idx <- min(chunk * chunk_size, nrow(Mica_values_df))
    lut_inv_list[[chunk]] <- sfLapply(start_idx:end_idx, process_row) %>% bind_rows()
  }
})

lut_inv <- bind_rows(lut_inv_list)

# Stop the cluster
sfStop()
ncell(Mica_rst)

# Create empty raster object and fill with LAI values
Mica_LAI_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
Mica_Cab_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)

# Create empty raster object and fill with LIDFa values
Mica_LIDFa_rst <- raster(Mica_rst@extent, nrows = nrow(Mica_rst), ncols = ncol(Mica_rst), crs = Mica_rst@crs)
values(Mica_LIDFa_rst) <- lut_inv$LIDFa
values(Mica_LAI_rst) <- lut_inv$lai
values(Mica_Cab_rst) <- lut_inv$CHL
# Specify the directory where you want to save the file
data_dir <- "E:/2023_process/20230710_final_process/"
writeRaster(Mica_LAI_rst, filename = file.path(data_dir, "Mica_LAI_20230710_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_Cab_rst, filename = file.path(data_dir, "Mica_Cab_20230710_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
writeRaster(Mica_LIDFa_rst, filename = file.path(data_dir, "Mica_LIDFa_20230710_1m.tif"), options = c("COMPRESS=DEFLATE"), overwrite = TRUE)
```
